/**
 * ╔══════════════════════════════════════════════════════════╗
 * ║       AUTO-GENERATED FILE - DO NOT EDIT MANUALLY         ║
 * ╚══════════════════════════════════════════════════════════╝
 *
 * SF Symbols Library - Compatibility Layer (v1.x API)
 *
 * @deprecated Use tree-shakeable imports instead:
 *   import { SFCheckmarkCircle } from 'sf-symbols-lib/hierarchical';
 *
 * Generated by: scripts/generate-sfsymbols.ts
 */

// Re-export all symbol names and constants
// eslint-disable-next-line react-refresh/only-export-components
export * from '@/components/sf-symbol-name';

export { SFSymbol, type SFSymbolProps } from '@/compat/SFSymbol';
export { default as SFSymbol_default } from '@/compat/SFSymbol';

export { SFSymbolVariant } from '@/types/symbol-types';
export { SFSymbolSize } from '@/types/sizes';
