/**
 * ╔══════════════════════════════════════════════════════════╗
 * ║       AUTO-GENERATED FILE - DO NOT EDIT MANUALLY         ║
 * ╚══════════════════════════════════════════════════════════╝
 *
 * Legacy SFSymbol renderer (Compat Layer)
 *
 * @deprecated Use tree-shakeable imports instead:
 *   Before: import { SFSymbol, SFCheckmarkCircle } from 'sf-symbols-lib'
 *   After:  import { SFCheckmarkCircle } from 'sf-symbols-lib/hierarchical'
 *
 * Generated by: scripts/generate-sfsymbols.ts
 */
import { type ReactElement, useEffect } from 'react';

import { sfSymbolsData as hierarchicalData, sfSymbolsViewBox as hierarchicalViewBox } from '@/compat/hierarchical/data';
import { sfSymbolsData as monochromeData, sfSymbolsViewBox as monochromeViewBox } from '@/compat/monochrome/data';
import { sfSymbolsData as multicolorData, sfSymbolsViewBox as multicolorViewBox } from '@/compat/multicolor/data';
import { sfSymbolsData as paletteData, sfSymbolsViewBox as paletteViewBox } from '@/compat/palette/data';

import { SFSymbolSize } from '@/types/sizes';
import { SFSymbolVariant } from '@/types/symbol-types';

export interface SFSymbolProps {
  name: string;
  size?: number | string;
  className?: string;
  strokeWidth?: number | string;
  color?: string;
  svgContent?: string;
  viewBox?: string;
  variant?: SFSymbolVariant;
  [key: string]: any;
}

let deprecationWarned = false;

export function SFSymbol({
  name,
  size = SFSymbolSize.lg,
  className = '',
  strokeWidth = 1,
  color,
  svgContent,
  viewBox,
  variant = SFSymbolVariant.monochrome,
  ...rest
}: SFSymbolProps): ReactElement {
  // One-time deprecation warning in development
  useEffect(() => {
    if (!deprecationWarned && process.env.NODE_ENV === 'development') {
      deprecationWarned = true;
      console.warn(
        'sf-symbols-lib: The SFSymbol component is deprecated and will be removed in v3.0.\n' +
        'Migrate to tree-shakeable imports for better bundle sizes:\n\n' +
        "  Before: import { SFSymbol, SFSymbolName } from 'sf-symbols-lib'\n" +
        "  After:  import { SFCheckmarkCircle } from 'sf-symbols-lib/hierarchical'\n\n" +
        'See: https://github.com/phranck/sf-symbols-lib#migration-v2'
      );
    }
  }, []);

  let numSize: number;
  if (typeof size === 'string') {
    numSize = SFSymbolSize[size.toLowerCase()] ?? parseInt(size, 10);
  } else {
    numSize = size;
  }

  // Resolve SVG data by variant + name
  let resolvedSvg: string | undefined = svgContent;
  let resolvedViewBox: string | undefined = viewBox;
  if (!resolvedSvg) {
    switch (variant) {
      case SFSymbolVariant.hierarchical:
        resolvedSvg = hierarchicalData[name as keyof typeof hierarchicalData];
        resolvedViewBox = resolvedViewBox || hierarchicalViewBox[name as keyof typeof hierarchicalViewBox];
        break;
      case SFSymbolVariant.palette:
        resolvedSvg = paletteData[name as keyof typeof paletteData];
        resolvedViewBox = resolvedViewBox || paletteViewBox[name as keyof typeof paletteViewBox];
        break;
      case SFSymbolVariant.multicolor:
        resolvedSvg = multicolorData[name as keyof typeof multicolorData];
        resolvedViewBox = resolvedViewBox || multicolorViewBox[name as keyof typeof multicolorViewBox];
        break;
      case SFSymbolVariant.monochrome:
      default:
        resolvedSvg = monochromeData[name as keyof typeof monochromeData];
        resolvedViewBox = resolvedViewBox || monochromeViewBox[name as keyof typeof monochromeViewBox];
        break;
    }
  }

  if (!resolvedSvg) {
    console.warn(`Symbol "${name}" not found for variant ${variant}`);
    return <svg /> as ReactElement;
  }

  const recolorRegex = /fill=(['"])(?:#(?:fff|ffffff)|white)\1/gi;
  const processedSvg = color ? resolvedSvg.replace(recolorRegex, `fill="${color}"`) : resolvedSvg;

  const shouldForceFill = !color && (variant === SFSymbolVariant.hierarchical || variant === SFSymbolVariant.monochrome);
  const svgFillAttr = shouldForceFill ? 'currentColor' : undefined;

  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={resolvedViewBox || `0 0 ${SFSymbolSize.lg} ${SFSymbolSize.lg}`}
      width={numSize}
      height={numSize}
      fill={svgFillAttr}
      strokeWidth={strokeWidth}
      className={className}
      style={{
        minWidth: numSize,
        minHeight: numSize,
        maxWidth: numSize,
        maxHeight: numSize,
        flex: `0 0 ${numSize}px`,
        ...((rest.style as any) || {}),
      }}
      {...rest}
      dangerouslySetInnerHTML={{ __html: processedSvg }}
    />
  ) as ReactElement;
}

export default SFSymbol;
