/**
 * ╔══════════════════════════════════════════════════════════╗
 * ║       AUTO-GENERATED FILE - DO NOT EDIT MANUALLY         ║
 * ╚══════════════════════════════════════════════════════════╝
 *
 * SF Symbols - multicolor
 *
 * Usage:
 * import { SFSymbol, Checkmark, CheckmarkCircleFill } from 'sf-symbols-lib/multicolor';
 *
 * <SFSymbol name={Checkmark} />
 *
 * Generated by: scripts/generate-sfsymbols.ts
 */

// Re-export all symbol names and constants
// eslint-disable-next-line react-refresh/only-export-components
export * from '@/components/sf-symbol-name';

export { default as SFSymbol } from '@/common/SFSymbol';
