/**
 * Available SF Symbols from SVG Files
 * 
 * SOURCE OF TRUTH: This enum is generated directly from SVG filenames in src/components/svgs/
 * All symbol references throughout the app should use keys from this enum.
 * This ensures type-safety and prevents referencing non-existent symbols.
 * 
 * Generated by: scripts/generate-sfsymbols.ts
 * DO NOT EDIT MANUALLY - Changes will be overwritten on next script run
 * 
 * Usage:
 * import { AvailableSFSymbol } from './available-sfsymbols';
 * 
 * // Use in mappings (e.g., section-symbols mapping)
 * const symbolMapping = {
 *   Display: AvailableSFSymbol.Display,  // Type-safe!
 * };
 */

export enum AvailableSFSymbol {
  AirplayVideo = 'airplay.video',
  AirplayVideoCircle = 'airplay.video.circle',
  AppleTerminal = 'apple.terminal',
  AppleTerminalFill = 'apple.terminal.fill',
  ArrowDownDocumentFill = 'arrow.down.document.fill',
  ArrowTrianglehead2ClockwiseRotate90 = 'arrow.trianglehead.2.clockwise.rotate.90',
  ArrowTrianglehead2ClockwiseRotate90Circle = 'arrow.trianglehead.2.clockwise.rotate.90.circle',
  ArrowTrianglehead2ClockwiseRotate90CircleFill = 'arrow.trianglehead.2.clockwise.rotate.90.circle.fill',
  ArrowUpDocumentFill = 'arrow.up.document.fill',
  Autostartstop = 'autostartstop',
  Bonjour = 'bonjour',
  BookPages = 'book.pages',
  BookPagesFill = 'book.pages.fill',
  Checkmark = 'checkmark',
  CheckmarkApp = 'checkmark.app',
  CheckmarkAppFill = 'checkmark.app.fill',
  CheckmarkBubble = 'checkmark.bubble',
  CheckmarkBubbleFill = 'checkmark.bubble.fill',
  CheckmarkCircle = 'checkmark.circle',
  CheckmarkCircleFill = 'checkmark.circle.fill',
  CheckmarkMessage = 'checkmark.message',
  CheckmarkMessageFill = 'checkmark.message.fill',
  CheckmarkSeal = 'checkmark.seal',
  CheckmarkSealFill = 'checkmark.seal.fill',
  CheckmarkSealTextPage = 'checkmark.seal.text.page',
  CheckmarkSealTextPageFill = 'checkmark.seal.text.page.fill',
  ChevronDown = 'chevron.down',
  ChevronDown2 = 'chevron.down.2',
  ChevronDownCircle = 'chevron.down.circle',
  ChevronDownCircleFill = 'chevron.down.circle.fill',
  ChevronUp = 'chevron.up',
  ChevronUp2 = 'chevron.up.2',
  ChevronUpCircle = 'chevron.up.circle',
  ChevronUpCircleFill = 'chevron.up.circle.fill',
  Circle = 'circle',
  Computermouse = 'computermouse',
  ComputermouseFill = 'computermouse.fill',
  Cpu = 'cpu',
  CpuFill = 'cpu.fill',
  Desktopcomputer = 'desktopcomputer',
  Display = 'display',
  Display2 = 'display.2',
  DisplayAndScrewdriver = 'display.and.screwdriver',
  DocumentBadgeArrowUpFill = 'document.badge.arrow.up.fill',
  DocumentBadgePlus = 'document.badge.plus',
  DocumentBadgePlusFill = 'document.badge.plus.fill',
  DocumentOnDocument = 'document.on.document',
  DocumentOnDocumentFill = 'document.on.document.fill',
  DocumentOnTrashFill = 'document.on.trash.fill',
  ExclamationmarkArrowTrianglehead2ClockwiseRotate90 = 'exclamationmark.arrow.trianglehead.2.clockwise.rotate.90',
  ExclamationmarkBubbleFill = 'exclamationmark.bubble.fill',
  Externaldrive = 'externaldrive',
  ExternaldriveConnectedToLineBelow = 'externaldrive.connected.to.line.below',
  ExternaldriveConnectedToLineBelowFill = 'externaldrive.connected.to.line.below.fill',
  ExternaldriveFill = 'externaldrive.fill',
  Hifispeaker = 'hifispeaker',
  Hifispeaker2 = 'hifispeaker.2',
  Hifispeaker2Fill = 'hifispeaker.2.fill',
  HifispeakerFill = 'hifispeaker.fill',
  InfoBubble = 'info.bubble',
  InfoBubbleFill = 'info.bubble.fill',
  InfoCircle = 'info.circle',
  InfoCircleFill = 'info.circle.fill',
  InfoCircleTextPage = 'info.circle.text.page',
  InfoSquare = 'info.square',
  InfoSquareFill = 'info.square.fill',
  InfoTriangle = 'info.triangle',
  InfoTriangleFill = 'info.triangle.fill',
  Internaldrive = 'internaldrive',
  InternaldriveFill = 'internaldrive.fill',
  Keyboard = 'keyboard',
  KeyboardBadgeEllipsis = 'keyboard.badge.ellipsis',
  KeyboardBadgeEllipsisFill = 'keyboard.badge.ellipsis.fill',
  KeyboardFill = 'keyboard.fill',
  KeyboardMacwindow = 'keyboard.macwindow',
  LinkIcloud = 'link.icloud',
  ListBulletClipboard = 'list.bullet.clipboard',
  ListBulletClipboardFill = 'list.bullet.clipboard.fill',
  LockDocumentFill = 'lock.document.fill',
  LongTextPageAndPencil = 'long.text.page.and.pencil',
  LongTextPageAndPencilFill = 'long.text.page.and.pencil.fill',
  Macwindow = 'macwindow',
  MacwindowOnRectangle = 'macwindow.on.rectangle',
  MacwindowStack = 'macwindow.stack',
  Memorychip = 'memorychip',
  MemorychipFill = 'memorychip.fill',
  MoonCircleFill = 'moon.circle.fill',
  MoonStars = 'moon.stars',
  MoonStarsCircle = 'moon.stars.circle',
  Network = 'network',
  Opticaldisc = 'opticaldisc',
  OpticaldiscFill = 'opticaldisc.fill',
  Opticaldiscdrive = 'opticaldiscdrive',
  OpticaldiscdriveFill = 'opticaldiscdrive.fill',
  Paintpalette = 'paintpalette',
  PaintpaletteFill = 'paintpalette.fill',
  PencilAndListClipboard = 'pencil.and.list.clipboard',
  Printer = 'printer',
  PrinterFill = 'printer.fill',
  Receipt = 'receipt',
  ReceiptFill = 'receipt.fill',
  RestartCircle = 'restart.circle',
  RestartCircleFill = 'restart.circle.fill',
  ScribbleVariable = 'scribble.variable',
  ServerRack = 'server.rack',
  SquareAndArrowDownFill = 'square.and.arrow.down.fill',
  SquareAndArrowDownOnSquare = 'square.and.arrow.down.on.square',
  SquareAndArrowDownOnSquareFill = 'square.and.arrow.down.on.square.fill',
  SquareAndArrowUpFill = 'square.and.arrow.up.fill',
  SquareAndArrowUpOnSquare = 'square.and.arrow.up.on.square',
  SquareAndArrowUpOnSquareFill = 'square.and.arrow.up.on.square.fill',
  SunMax = 'sun.max',
  SunMaxCircle = 'sun.max.circle',
  SunMaxCircleFill = 'sun.max.circle.fill',
  SunMaxFill = 'sun.max.fill',
  TextAndCommandMacwindow = 'text.and.command.macwindow',
  TextLineFirstAndArrowtriangleForward = 'text.line.first.and.arrowtriangle.forward',
  TextRectangleFill = 'text.rectangle.fill',
  TextRedaction = 'text.redaction',
  Trash = 'trash',
  TrashCircle = 'trash.circle',
  TrashCircleFill = 'trash.circle.fill',
  TrashFill = 'trash.fill',
  TrashSquare = 'trash.square',
  TrashSquareFill = 'trash.square.fill',
  Tray2 = 'tray.2',
  Tray2Fill = 'tray.2.fill',
  TrayAndArrowDown = 'tray.and.arrow.down',
  TrayAndArrowDownFill = 'tray.and.arrow.down.fill',
  TrayAndArrowUp = 'tray.and.arrow.up',
  TrayAndArrowUpFill = 'tray.and.arrow.up.fill',
  Video = 'video',
  VideoBadgeWaveform = 'video.badge.waveform',
  VideoBadgeWaveformFill = 'video.badge.waveform.fill',
  VideoBubble = 'video.bubble',
  VideoBubbleFill = 'video.bubble.fill',
  VideoFill = 'video.fill',
  Videoprojector = 'videoprojector',
  VideoprojectorFill = 'videoprojector.fill',
  Wifi = 'wifi',
  WifiCircle = 'wifi.circle',
  WifiCircleFill = 'wifi.circle.fill',
  WifiRouter = 'wifi.router',
  WifiRouterFill = 'wifi.router.fill',
  WifiSquare = 'wifi.square',
  WifiSquareFill = 'wifi.square.fill',
}

export type AvailableSFSymbolType = `${AvailableSFSymbol}`;

/**
 * Get all available symbol values as an array
 * Useful for validation and iteration
 */
export function getAvailableSymbols(): string[] {
  return Object.values(AvailableSFSymbol);
}

/**
 * Check if a symbol value is available
 * @param symbolValue The symbol value to check
 * @returns true if the symbol is available, false otherwise
 */
export function isAvailableSymbol(symbolValue: string): boolean {
  return Object.values(AvailableSFSymbol).includes(symbolValue as AvailableSFSymbol);
}
