/**
 * SF Symbols - monochrome
 *
 * Usage:
 * import { SFSymbol, Checkmark, CheckmarkCircleFill } from 'sf-symbols-lib/monochrome';
 *
 * <SFSymbol name={Checkmark} />
 *
 * Generated by: scripts/generate-sfsymbols.ts
 * DO NOT EDIT MANUALLY
 */

// Re-export all symbol names and constants
export * from '@/components/sf-symbol-name';

export { default as SFSymbol } from '@/common/SFSymbol';
