/**
 * TEST GENERATOR: Generates only 10 icons for testing
 * Run with: tsx scripts/generate-sfsymbols-test.ts
 */

import fs from 'fs';
import path from 'path';

const VARIANTS = ['hierarchical', 'monochrome'] as const;

interface IconData {
  fileName: string;
  pascalName: string;
  svgContent: string;
  viewBox: string;
}

function kebabToPascalCase(kebabStr: string): string {
  const result = kebabStr
    .split(/[-.]/)
    .filter(word => word.length > 0)
    .map(word => {
      if (/^\d+$/.test(word)) return word;
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join('');
  return 'SF' + result;
}

function extractViewBox(svgPath: string): string {
  const content = fs.readFileSync(svgPath, 'utf-8');
  const viewBoxMatch = content.match(/viewBox="([^"]*)"/);
  return viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24';
}

function extractSvgContent(svgPath: string): string {
  let content = fs.readFileSync(svgPath, 'utf-8');
  content = content.replace(/<\?xml[^?]*\?>/g, '').trim();
  content = content.replace(/<!DOCTYPE[^>]*>/g, '').trim();
  content = content.replace(/<!--[\s\S]*?-->/g, '').trim();
  content = content.replace(/>\s+</g, '><');
  content = content.replace(/fill="(white|black|#[0-9a-fA-F]{6}|#[0-9a-fA-F]{3})"/g, 'fill="currentColor"');
  const svgMatch = content.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  return svgMatch ? svgMatch[1].trim() : content;
}

function ensureDir(dirPath: string): void {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function parseIconData(svgPath: string, fileName: string): IconData {
  return {
    fileName,
    pascalName: kebabToPascalCase(fileName),
    svgContent: extractSvgContent(svgPath),
    viewBox: extractViewBox(svgPath),
  };
}

function generateIconComponent(icon: IconData): string {
  const escapedSvgContent = icon.svgContent
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');

  return `/**
 * ╔══════════════════════════════════════════════════════════╗
 * ║       AUTO-GENERATED FILE - DO NOT EDIT MANUALLY         ║
 * ╚══════════════════════════════════════════════════════════╝
 *
 * ${icon.pascalName}
 * Generated by: scripts/generate-sfsymbols-test.ts
 */

import React from 'react';

export interface ${icon.pascalName}Props {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  className?: string;
  color?: string;
  strokeWidth?: number;
  title?: string;
  'aria-label'?: string;
}

const SIZE_MAP = {
  xs: 16,
  sm: 20,
  md: 24,
  lg: 32,
  xl: 48,
} as const;

export function ${icon.pascalName}({
  size = 'md',
  className,
  color,
  strokeWidth = 1,
  title,
  'aria-label': ariaLabel,
}: ${icon.pascalName}Props): React.JSX.Element {
  const dimensions = SIZE_MAP[size];
  
  return (
    <svg
      width={dimensions}
      height={dimensions}
      viewBox="${icon.viewBox}"
      className={className}
      style={{ color }}
      strokeWidth={strokeWidth}
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
      role={title || ariaLabel ? 'img' : undefined}
      aria-label={ariaLabel}
    >
      {title && <title>{title}</title>}
      <g dangerouslySetInnerHTML={{ __html: \`${escapedSvgContent}\` }} />
    </svg>
  );
}

export default ${icon.pascalName};
`;
}

function generateBarrelExport(icons: IconData[]): string {
  const sortedIcons = [...icons].sort((a, b) => a.pascalName.localeCompare(b.pascalName));
  
  const exportStatements = sortedIcons
    .map(icon => `export { ${icon.pascalName}, default as ${icon.pascalName}Default } from './${icon.pascalName}';`)
    .join('\n');

  const typeExports = sortedIcons
    .map(icon => `export type { ${icon.pascalName}Props } from './${icon.pascalName}';`)
    .join('\n');

  return `/**
 * ╔══════════════════════════════════════════════════════════╗
 * ║       AUTO-GENERATED FILE - DO NOT EDIT MANUALLY         ║
 * ╚══════════════════════════════════════════════════════════╝
 *
 * Tree-Shakeable SF Symbols - TEST (${icons.length} icons)
 */

${exportStatements}

${typeExports}
`;
}

async function generateTestIcons() {
  console.log('\n🧪 TEST GENERATOR: Generating 10 icons for testing\n');
  
  const svgsDir = path.join(process.cwd(), '.svgs');
  const srcDir = path.join(process.cwd(), 'src');
  
  const hierarchicalDir = path.join(svgsDir, 'hierarchical');
  if (!fs.existsSync(hierarchicalDir)) {
    console.error(`❌ ERROR: ${hierarchicalDir} not found`);
    return;
  }
  
  // Get first 10 icons only
  const allFiles = fs.readdirSync(hierarchicalDir)
    .filter(file => file.endsWith('.svg'))
    .map(file => file.replace('.svg', ''))
    .slice(0, 10);
  
  console.log(`📦 Processing ${allFiles.length} test icons:\n`);
  allFiles.forEach((name, i) => console.log(`  ${i + 1}. ${name}`));
  console.log();
  
  for (const variant of VARIANTS) {
    const variantDir = path.join(svgsDir, variant);
    if (!fs.existsSync(variantDir)) {
      console.log(`⚠️  Skipping ${variant} (not found)`);
      continue;
    }
    
    const icons: IconData[] = [];
    
    for (const fileName of allFiles) {
      const svgPath = path.join(variantDir, `${fileName}.svg`);
      if (fs.existsSync(svgPath)) {
        icons.push(parseIconData(svgPath, fileName));
      }
    }
    
    // Generate files
    const outputDir = path.join(srcDir, variant);
    ensureDir(outputDir);
    
    console.log(`\n📝 Generating ${icons.length} components for ${variant}...`);
    
    for (const icon of icons) {
      const componentCode = generateIconComponent(icon);
      const filePath = path.join(outputDir, `${icon.pascalName}.tsx`);
      fs.writeFileSync(filePath, componentCode);
      console.log(`  ✓ ${icon.pascalName}.tsx`);
    }
    
    // Generate barrel export
    const barrelCode = generateBarrelExport(icons);
    const barrelPath = path.join(outputDir, 'index.tsx');
    fs.writeFileSync(barrelPath, barrelCode);
    console.log(`  ✓ index.tsx (barrel export)`);
    
    console.log(`\n✅ Generated ${icons.length} tree-shakeable icons for ${variant}`);
  }
  
  console.log('\n📊 Summary:');
  console.log(`  - Generated: ${allFiles.length} icons × ${VARIANTS.length} variants = ${allFiles.length * VARIANTS.length} files`);
  console.log(`  - Location: src/hierarchical/ and src/monochrome/`);
  console.log('\n🎯 Next steps:');
  console.log('  1. Check the generated files in src/hierarchical/');
  console.log('  2. Run: npm run build');
  console.log('  3. Check dist/hierarchical/ for bundled output');
  console.log('  4. Open test-treeshake.html in browser\n');
}

generateTestIcons().catch(error => {
  console.error('❌ Error:', error);
  process.exit(1);
});
