/**
 * Generate the icon catalog for the docs-app.
 *
 * Reads SVG metadata from .svgs/dualtone/ and produces a TypeScript file
 * with all icon entries (name, pascalName, categories, restricted) plus
 * a sorted list of unique categories.
 *
 * Output: docs-app/src/lib/catalog.ts
 *
 * Usage: tsx scripts/generate-catalog.ts
 */
import fs from 'fs';
import path from 'path';

import { kebabToPascalCase, parseMetadataFromContent } from './shared/utils';

interface CatalogEntry {
  name: string;
  pascalName: string;
  categories: string[];
  restricted: boolean;
}

function generateCatalog(): void {
  const svgsDir = path.join(process.cwd(), '.svgs', 'dualtone');

  if (!fs.existsSync(svgsDir)) {
    console.error(`ERROR: SVG directory not found: ${svgsDir}`);
    process.exit(1);
  }

  const svgFiles = fs
    .readdirSync(svgsDir)
    .filter((f) => f.endsWith('.svg'))
    .sort();

  if (svgFiles.length === 0) {
    console.error('ERROR: No SVG files found.');
    process.exit(1);
  }

  console.log(`Found ${svgFiles.length} SVG files, extracting metadata...`);

  const entries: CatalogEntry[] = [];
  const categorySet = new Set<string>();

  for (const file of svgFiles) {
    const name = file.replace('.svg', '');
    const pascalName = kebabToPascalCase(name);
    const content = fs.readFileSync(path.join(svgsDir, file), 'utf-8');
    const metadata = parseMetadataFromContent(content);

    const categories = metadata?.categories ?? [];
    const restricted = metadata?.restricted ?? false;

    entries.push({ name, pascalName, categories, restricted });

    for (const cat of categories) {
      categorySet.add(cat);
    }
  }

  const sortedCategories = [...categorySet].sort();

  // Generate TypeScript output
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * AUTO-GENERATED - DO NOT EDIT');
  lines.push(` * ${entries.length} icons from SF Symbols 7.1`);
  lines.push(' * Generated by: scripts/generate-catalog.ts');
  lines.push(' */');
  lines.push('');
  lines.push('export interface CatalogEntry {');
  lines.push('  name: string;');
  lines.push('  pascalName: string;');
  lines.push('  categories: string[];');
  lines.push('  restricted: boolean;');
  lines.push('}');
  lines.push('');
  lines.push('export const catalog: ReadonlyArray<CatalogEntry> = [');

  for (const entry of entries) {
    const cats = JSON.stringify(entry.categories);
    lines.push(
      `  { name: ${JSON.stringify(entry.name)}, pascalName: ${JSON.stringify(entry.pascalName)}, categories: ${cats}, restricted: ${entry.restricted} },`,
    );
  }

  lines.push('];');
  lines.push('');
  lines.push(
    'export const categories: ReadonlyArray<string> = [',
  );
  lines.push(`  ${sortedCategories.map((c) => JSON.stringify(c)).join(', ')},`);
  lines.push('];');
  lines.push('');

  // Write output
  const outputDir = path.join(process.cwd(), 'docs-app', 'src', 'lib');
  fs.mkdirSync(outputDir, { recursive: true });

  const outputPath = path.join(outputDir, 'catalog.ts');
  fs.writeFileSync(outputPath, lines.join('\n'));

  const restrictedCount = entries.filter((e) => e.restricted).length;
  console.log(`Generated catalog: ${entries.length} icons, ${sortedCategories.length} categories, ${restrictedCount} restricted`);
  console.log(`Output: ${outputPath}`);
}

generateCatalog();
