import fs from 'fs';
import path from 'path';

import {
  RENDER_MODES,
  type RenderMode,
  type ParsedSvgEntry,
  kebabToPascalCase,
  parseSvgFile,
  ensureDir,
} from './shared/utils';

// ---------------------------------------------------------------------------
// Individual icon file generation (tree-shakeable API)
// ---------------------------------------------------------------------------

/**
 * Generate a single icon component file.
 *
 * Creates a standalone React component that wraps the parsed SVG data
 * with the shared `SFIcon` renderer and `forwardRef`.
 */
function generateIconComponentFile(
  outputDir: string,
  renderMode: RenderMode,
  pascalName: string,
  entry: ParsedSvgEntry,
): void {
  const escapedContent = entry.content
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, ' ')
    .replace(/\s+/g, ' ');

  const fileContent = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Icon: ${pascalName} (${renderMode})
 */
import { forwardRef } from 'react';

import { SFIcon } from '@/common/SFIcon';
import { type SFIconProps } from '@/common/types';

const SVG_CONTENT = '${escapedContent}';
const VIEW_BOX = '${entry.viewBox}';

/** ${pascalName} icon component (${renderMode}) */
export const ${pascalName} = forwardRef<SVGSVGElement, SFIconProps>((props, ref) => (
  <SFIcon ref={ref} svgContent={SVG_CONTENT} viewBox={VIEW_BOX} {...props} />
));

${pascalName}.displayName = '${pascalName}';

export default ${pascalName};
`;

  const dirPath = path.join(outputDir, renderMode, 'icons');
  ensureDir(dirPath);
  fs.writeFileSync(path.join(dirPath, `${pascalName}.tsx`), fileContent);
}

/**
 * Generate barrel export that re-exports all individual icon components.
 *
 * Creates a single `index.tsx` per render mode that re-exports every icon,
 * the shared types, the generic renderer, and the context provider.
 */
function generateBarrelExport(
  outputDir: string,
  renderMode: RenderMode,
  pascalNames: string[],
): void {
  const sorted = [...pascalNames].sort();

  const exports = sorted
    .map((name) => `export { ${name} } from '@/${renderMode}/icons/${name}';`)
    .join('\n');

  const fileContent = `/**
 * ╔══════════════════════════════════════════════════════════╗
 * ║       AUTO-GENERATED FILE - DO NOT EDIT MANUALLY         ║
 * ╚══════════════════════════════════════════════════════════╝
 *
 * SF Symbols - ${renderMode} (Tree-Shakeable API)
 *
 * Usage:
 *   import { SFCheckmarkCircleFill, SFPhone } from 'sf-symbols-lib/${renderMode}';
 *   <SFCheckmarkCircleFill size="lg" />
 *
 * Each icon is a standalone React component. Only imported icons
 * are included in the consumer bundle.
 *
 * Generated by: scripts/generate-sfsymbols.ts
 */

// Re-export shared types
export type { SFIconProps, SFIconSize, SFIconSizePreset } from '@/common/types';

// Re-export the generic renderer for advanced use cases
export { SFIcon } from '@/common/SFIcon';

// Re-export context for global icon defaults
export { SFIconContext } from '@/common/context';

// Individual icon components (${sorted.length} icons)
${exports}
`;

  const dirPath = path.join(outputDir, renderMode);
  ensureDir(dirPath);
  fs.writeFileSync(path.join(dirPath, 'index.tsx'), fileContent);
  console.log(
    `✅ CREATED: ${renderMode}/index.tsx (barrel, ${sorted.length} re-exports)`,
  );
}

// ---------------------------------------------------------------------------
// Main index.ts generation
// ---------------------------------------------------------------------------

/**
 * Generate main index.ts that re-exports dualtone as the default render mode
 */
function generateMainIndex(srcDir: string): void {
  const fileContent = `/**
 * ╔══════════════════════════════════════════════════════════╗
 * ║       AUTO-GENERATED FILE - DO NOT EDIT MANUALLY         ║
 * ╚══════════════════════════════════════════════════════════╝
 *
 * SF Symbols Library
 *
 * The default export re-exports the dualtone render mode.
 * For a specific render mode, import directly:
 *   import { SFCheckmarkCircle } from 'sf-symbols-lib/dualtone';
 *   import { SFCheckmarkCircle } from 'sf-symbols-lib/monochrome';
 *
 * Generated by: scripts/generate-sfsymbols.ts
 */

// Re-export dualtone as default render mode
export * from './dualtone';
`;

  fs.writeFileSync(path.join(srcDir, 'index.ts'), fileContent);
  console.log('✅ CREATED: index.ts (default: dualtone)');
}

// ---------------------------------------------------------------------------
// README / package.json updates
// ---------------------------------------------------------------------------

/** Update the SF Symbols count badge and text in README.md */
function updateReadmeSymbolCount(symbolCount: number): void {
  const readmePath = path.join(process.cwd(), 'README.md');
  if (!fs.existsSync(readmePath)) return;

  let content = fs.readFileSync(readmePath, 'utf-8');
  const formatted = symbolCount.toLocaleString();

  const badgeUrl = `https://img.shields.io/badge/SF%20Symbols-${symbolCount}-blue?style=flat-square&logo=apple&logoColor=white`;
  content = content.replace(
    /!\[SF Symbols\]\([^)]+\)/,
    `![SF Symbols](${badgeUrl})`,
  );
  content = content.replace(
    /A React component library providing \*\*[\d,]+\s+SF Symbols\*\*/,
    `A React component library providing **${formatted} SF Symbols**`,
  );
  content = content.replace(
    /^- \*\*[\d,]+\s+Symbols\*\*/m,
    `- **${formatted} Symbols**`,
  );

  fs.writeFileSync(readmePath, content);
  console.log(`✅ UPDATED: README.md with ${symbolCount} symbols`);
}

/** Update the symbol count in package.json description */
function updatePackageJsonSymbolCount(symbolCount: number): void {
  const pkgPath = path.join(process.cwd(), 'package.json');
  if (!fs.existsSync(pkgPath)) return;

  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
  if (pkg.description) {
    pkg.description = pkg.description.replace(
      /SF Symbols \([\d,]+\)/,
      `SF Symbols (${symbolCount.toLocaleString()})`,
    );
  }

  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
  console.log(
    `✅ UPDATED: package.json description with ${symbolCount} symbols`,
  );
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function generateSFSymbols() {
  const svgsDir = path.join(process.cwd(), '.svgs');
  const srcDir = path.join(process.cwd(), 'src');

  const dualtoneDir = path.join(svgsDir, 'dualtone');
  if (!fs.existsSync(dualtoneDir)) {
    console.error(
      `❌ ERROR: Expected directory structure not found: ${dualtoneDir}`,
    );
    process.exit(1);
  }

  const symbolFileNames = fs
    .readdirSync(dualtoneDir)
    .filter((file) => file.endsWith('.svg'))
    .map((file) => file.replace('.svg', ''));

  if (symbolFileNames.length === 0) {
    console.error('❌ No SVG files found.');
    process.exit(1);
  }

  console.log(`\n🔍 Found ${symbolFileNames.length} symbols\n`);

  // Step 1: Process each render mode - generate individual icon components
  let totalProcessed = 0;

  for (const renderMode of RENDER_MODES) {
    const modeSvgDir = path.join(svgsDir, renderMode);
    if (!fs.existsSync(modeSvgDir)) {
      console.warn(`⚠️  Directory not found: ${modeSvgDir}`);
      continue;
    }

    const pascalNames: string[] = [];
    let modeCount = 0;

    for (const fileName of symbolFileNames) {
      const svgPath = path.join(modeSvgDir, `${fileName}.svg`);
      if (!fs.existsSync(svgPath)) continue;

      const pascalName = kebabToPascalCase(fileName);

      try {
        const entry = parseSvgFile(svgPath);

        // Cross-validate lib name
        if (
          entry.metadata?.libName &&
          entry.metadata.libName !== pascalName
        ) {
          console.warn(
            `⚠️  Name mismatch for ${fileName}: embedded="${entry.metadata.libName}" vs generated="${pascalName}"`,
          );
        }

        generateIconComponentFile(srcDir, renderMode, pascalName, entry);
        pascalNames.push(pascalName);
        modeCount++;
        totalProcessed++;
      } catch (error) {
        console.error(
          `❌ ERROR processing ${svgPath}:`,
          error instanceof Error ? error.message : error,
        );
      }
    }

    // Generate barrel export
    generateBarrelExport(srcDir, renderMode, pascalNames);
    console.log(`✓ ${renderMode}: ${modeCount} icons`);
  }

  // Step 2: Generate main index.ts (re-exports dualtone)
  generateMainIndex(srcDir);

  // Step 3: Update README and package.json
  updateReadmeSymbolCount(symbolFileNames.length);
  updatePackageJsonSymbolCount(symbolFileNames.length);

  console.log(
    `\n📊 Summary: ${symbolFileNames.length} symbols x ${RENDER_MODES.length} render modes = ${totalProcessed} individual icon components\n`,
  );
}

generateSFSymbols().catch((error) => {
  console.error('❌ Error generating SF Symbols:', error);
  process.exit(1);
});
