/**
 * SF Symbols Icon Library - Index File
 *
 * This file is auto-generated by the generate-sf-symbols script.
 * It exports all SF Symbol icon components for easy importing.
 * Uses SFSymbolName enum for type-safe icon references.
 *
 * Usage:
 * import { SFCheckmark, SFCircle } from 'sf-symbols-lib';
 */

/**
 * SF Symbols Icon Library - Index File
 *
 * This file is auto-generated by the generate-sf-symbols script.
 * It exports all SF Symbol icon components for easy importing.
 * Uses SFSymbolName enum for type-safe icon references.
 *
 * Usage:
 * import { SFCheckmark, SFCircle } from 'sf-symbols-lib';
 */

import { AvailableSFSymbol } from './components/available-sfsymbols';
import { createSFIcon, type SFIconProps } from './components/SFIcon';

// Define all icons first with explicit types
const SFAirplayVideo: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.AirplayVideo);
const SFAirplayVideoCircle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.AirplayVideoCircle);
const SFArrowDownDocumentFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ArrowDownDocumentFill);
const SFArrowTrianglehead2ClockwiseRotate90: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ArrowTrianglehead2ClockwiseRotate90);
const SFArrowTrianglehead2ClockwiseRotate90Circle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ArrowTrianglehead2ClockwiseRotate90Circle);
const SFArrowTrianglehead2ClockwiseRotate90CircleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ArrowTrianglehead2ClockwiseRotate90CircleFill);
const SFArrowUpDocumentFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ArrowUpDocumentFill);
const SFAutostartstop: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Autostartstop);
const SFBonjour: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Bonjour);
const SFCheckmark: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Checkmark);
const SFCheckmarkApp: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.CheckmarkApp);
const SFCheckmarkAppFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.CheckmarkAppFill);
const SFCheckmarkBubble: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.CheckmarkBubble);
const SFCheckmarkBubbleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.CheckmarkBubbleFill);
const SFCheckmarkCircle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.CheckmarkCircle);
const SFCheckmarkCircleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.CheckmarkCircleFill);
const SFCheckmarkMessage: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.CheckmarkMessage);
const SFCheckmarkMessageFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.CheckmarkMessageFill);
const SFCheckmarkSeal: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.CheckmarkSeal);
const SFCheckmarkSealFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.CheckmarkSealFill);
const SFChevronDown: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ChevronDown);
const SFChevronDown2: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ChevronDown2);
const SFChevronDownCircle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ChevronDownCircle);
const SFChevronDownCircleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ChevronDownCircleFill);
const SFChevronUp: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ChevronUp);
const SFChevronUp2: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ChevronUp2);
const SFChevronUpCircle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ChevronUpCircle);
const SFChevronUpCircleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ChevronUpCircleFill);
const SFCircle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Circle);
const SFComputermouse: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Computermouse);
const SFComputermouseFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ComputermouseFill);
const SFCpu: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Cpu);
const SFCpuFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.CpuFill);
const SFDesktopcomputer: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Desktopcomputer);
const SFDisplay: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Display);
const SFDisplay2: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Display2);
const SFDisplayAndScrewdriver: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.DisplayAndScrewdriver);
const SFDocumentBadgeArrowUpFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.DocumentBadgeArrowUpFill);
const SFDocumentBadgePlus: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.DocumentBadgePlus);
const SFDocumentBadgePlusFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.DocumentBadgePlusFill);
const SFDocumentOnDocument: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.DocumentOnDocument);
const SFDocumentOnDocumentFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.DocumentOnDocumentFill);
const SFDocumentOnTrashFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.DocumentOnTrashFill);
const SFExclamationmarkArrowTrianglehead2ClockwiseRotate90: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ExclamationmarkArrowTrianglehead2ClockwiseRotate90);
const SFExclamationmarkBubbleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ExclamationmarkBubbleFill);
const SFExternaldrive: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Externaldrive);
const SFExternaldriveConnectedToLineBelow: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ExternaldriveConnectedToLineBelow);
const SFExternaldriveConnectedToLineBelowFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ExternaldriveConnectedToLineBelowFill);
const SFExternaldriveFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ExternaldriveFill);
const SFHifispeaker: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Hifispeaker);
const SFHifispeaker2: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Hifispeaker2);
const SFHifispeaker2Fill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Hifispeaker2Fill);
const SFHifispeakerFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.HifispeakerFill);
const SFInfoBubble: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.InfoBubble);
const SFInfoBubbleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.InfoBubbleFill);
const SFInfoCircle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.InfoCircle);
const SFInfoCircleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.InfoCircleFill);
const SFInfoSquare: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.InfoSquare);
const SFInfoSquareFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.InfoSquareFill);
const SFInfoTriangle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.InfoTriangle);
const SFInfoTriangleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.InfoTriangleFill);
const SFInternaldrive: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Internaldrive);
const SFInternaldriveFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.InternaldriveFill);
const SFKeyboard: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Keyboard);
const SFKeyboardBadgeEllipsis: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.KeyboardBadgeEllipsis);
const SFKeyboardBadgeEllipsisFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.KeyboardBadgeEllipsisFill);
const SFKeyboardFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.KeyboardFill);
const SFKeyboardMacwindow: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.KeyboardMacwindow);
const SFLinkIcloud: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.LinkIcloud);
const SFListBulletClipboard: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ListBulletClipboard);
const SFListBulletClipboardFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ListBulletClipboardFill);
const SFLockDocumentFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.LockDocumentFill);
const SFLongTextPageAndPencil: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.LongTextPageAndPencil);
const SFLongTextPageAndPencilFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.LongTextPageAndPencilFill);
const SFMacwindow: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Macwindow);
const SFMacwindowOnRectangle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.MacwindowOnRectangle);
const SFMacwindowStack: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.MacwindowStack);
const SFMemorychip: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Memorychip);
const SFMemorychipFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.MemorychipFill);
const SFMoonCircleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.MoonCircleFill);
const SFMoonStars: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.MoonStars);
const SFMoonStarsCircle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.MoonStarsCircle);
const SFNetwork: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Network);
const SFOpticaldisc: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Opticaldisc);
const SFOpticaldiscFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.OpticaldiscFill);
const SFOpticaldiscdrive: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Opticaldiscdrive);
const SFOpticaldiscdriveFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.OpticaldiscdriveFill);
const SFPaintpalette: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Paintpalette);
const SFPaintpaletteFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.PaintpaletteFill);
const SFPencilAndListClipboard: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.PencilAndListClipboard);
const SFPrinter: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Printer);
const SFPrinterFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.PrinterFill);
const SFRestartCircle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.RestartCircle);
const SFRestartCircleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.RestartCircleFill);
const SFScribbleVariable: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ScribbleVariable);
const SFServerRack: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.ServerRack);
const SFSquareAndArrowDownFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.SquareAndArrowDownFill);
const SFSquareAndArrowDownOnSquare: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.SquareAndArrowDownOnSquare);
const SFSquareAndArrowDownOnSquareFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.SquareAndArrowDownOnSquareFill);
const SFSquareAndArrowUpFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.SquareAndArrowUpFill);
const SFSquareAndArrowUpOnSquare: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.SquareAndArrowUpOnSquare);
const SFSquareAndArrowUpOnSquareFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.SquareAndArrowUpOnSquareFill);
const SFSunMax: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.SunMax);
const SFSunMaxCircle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.SunMaxCircle);
const SFSunMaxCircleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.SunMaxCircleFill);
const SFSunMaxFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.SunMaxFill);
const SFTextAndCommandMacwindow: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TextAndCommandMacwindow);
const SFTextLineFirstAndArrowtriangleForward: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TextLineFirstAndArrowtriangleForward);
const SFTextRectangleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TextRectangleFill);
const SFTextRedaction: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TextRedaction);
const SFTrash: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Trash);
const SFTrashCircle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TrashCircle);
const SFTrashCircleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TrashCircleFill);
const SFTrashFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TrashFill);
const SFTrashSquare: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TrashSquare);
const SFTrashSquareFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TrashSquareFill);
const SFTray2: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Tray2);
const SFTray2Fill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Tray2Fill);
const SFTrayAndArrowDown: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TrayAndArrowDown);
const SFTrayAndArrowDownFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TrayAndArrowDownFill);
const SFTrayAndArrowUp: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TrayAndArrowUp);
const SFTrayAndArrowUpFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.TrayAndArrowUpFill);
const SFVideo: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Video);
const SFVideoBadgeWaveform: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.VideoBadgeWaveform);
const SFVideoBadgeWaveformFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.VideoBadgeWaveformFill);
const SFVideoBubble: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.VideoBubble);
const SFVideoBubbleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.VideoBubbleFill);
const SFVideoFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.VideoFill);
const SFVideoprojector: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Videoprojector);
const SFVideoprojectorFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.VideoprojectorFill);
const SFWifi: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.Wifi);
const SFWifiCircle: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.WifiCircle);
const SFWifiCircleFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.WifiCircleFill);
const SFWifiRouter: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.WifiRouter);
const SFWifiRouterFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.WifiRouterFill);
const SFWifiSquare: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.WifiSquare);
const SFWifiSquareFill: React.ComponentType<SFIconProps> = createSFIcon(AvailableSFSymbol.WifiSquareFill);

// Export all icons
export {
  SFAirplayVideo,
  SFAirplayVideoCircle,
  SFArrowDownDocumentFill,
  SFArrowTrianglehead2ClockwiseRotate90,
  SFArrowTrianglehead2ClockwiseRotate90Circle,
  SFArrowTrianglehead2ClockwiseRotate90CircleFill,
  SFArrowUpDocumentFill,
  SFAutostartstop,
  SFBonjour,
  SFCheckmark,
  SFCheckmarkApp,
  SFCheckmarkAppFill,
  SFCheckmarkBubble,
  SFCheckmarkBubbleFill,
  SFCheckmarkCircle,
  SFCheckmarkCircleFill,
  SFCheckmarkMessage,
  SFCheckmarkMessageFill,
  SFCheckmarkSeal,
  SFCheckmarkSealFill,
  SFChevronDown,
  SFChevronDown2,
  SFChevronDownCircle,
  SFChevronDownCircleFill,
  SFChevronUp,
  SFChevronUp2,
  SFChevronUpCircle,
  SFChevronUpCircleFill,
  SFCircle,
  SFComputermouse,
  SFComputermouseFill,
  SFCpu,
  SFCpuFill,
  SFDesktopcomputer,
  SFDisplay,
  SFDisplay2,
  SFDisplayAndScrewdriver,
  SFDocumentBadgeArrowUpFill,
  SFDocumentBadgePlus,
  SFDocumentBadgePlusFill,
  SFDocumentOnDocument,
  SFDocumentOnDocumentFill,
  SFDocumentOnTrashFill,
  SFExclamationmarkArrowTrianglehead2ClockwiseRotate90,
  SFExclamationmarkBubbleFill,
  SFExternaldrive,
  SFExternaldriveConnectedToLineBelow,
  SFExternaldriveConnectedToLineBelowFill,
  SFExternaldriveFill,
  SFHifispeaker,
  SFHifispeaker2,
  SFHifispeaker2Fill,
  SFHifispeakerFill,
  SFInfoBubble,
  SFInfoBubbleFill,
  SFInfoCircle,
  SFInfoCircleFill,
  SFInfoSquare,
  SFInfoSquareFill,
  SFInfoTriangle,
  SFInfoTriangleFill,
  SFInternaldrive,
  SFInternaldriveFill,
  SFKeyboard,
  SFKeyboardBadgeEllipsis,
  SFKeyboardBadgeEllipsisFill,
  SFKeyboardFill,
  SFKeyboardMacwindow,
  SFLinkIcloud,
  SFListBulletClipboard,
  SFListBulletClipboardFill,
  SFLockDocumentFill,
  SFLongTextPageAndPencil,
  SFLongTextPageAndPencilFill,
  SFMacwindow,
  SFMacwindowOnRectangle,
  SFMacwindowStack,
  SFMemorychip,
  SFMemorychipFill,
  SFMoonCircleFill,
  SFMoonStars,
  SFMoonStarsCircle,
  SFNetwork,
  SFOpticaldisc,
  SFOpticaldiscFill,
  SFOpticaldiscdrive,
  SFOpticaldiscdriveFill,
  SFPaintpalette,
  SFPaintpaletteFill,
  SFPencilAndListClipboard,
  SFPrinter,
  SFPrinterFill,
  SFRestartCircle,
  SFRestartCircleFill,
  SFScribbleVariable,
  SFServerRack,
  SFSquareAndArrowDownFill,
  SFSquareAndArrowDownOnSquare,
  SFSquareAndArrowDownOnSquareFill,
  SFSquareAndArrowUpFill,
  SFSquareAndArrowUpOnSquare,
  SFSquareAndArrowUpOnSquareFill,
  SFSunMax,
  SFSunMaxCircle,
  SFSunMaxCircleFill,
  SFSunMaxFill,
  SFTextAndCommandMacwindow,
  SFTextLineFirstAndArrowtriangleForward,
  SFTextRectangleFill,
  SFTextRedaction,
  SFTrash,
  SFTrashCircle,
  SFTrashCircleFill,
  SFTrashFill,
  SFTrashSquare,
  SFTrashSquareFill,
  SFTray2,
  SFTray2Fill,
  SFTrayAndArrowDown,
  SFTrayAndArrowDownFill,
  SFTrayAndArrowUp,
  SFTrayAndArrowUpFill,
  SFVideo,
  SFVideoBadgeWaveform,
  SFVideoBadgeWaveformFill,
  SFVideoBubble,
  SFVideoBubbleFill,
  SFVideoFill,
  SFVideoprojector,
  SFVideoprojectorFill,
  SFWifi,
  SFWifiCircle,
  SFWifiCircleFill,
  SFWifiRouter,
  SFWifiRouterFill,
  SFWifiSquare,
  SFWifiSquareFill,
};

// Export types
export type { SFIconProps } from './components/SFIcon';

// Export icon map and enum for advanced usage
export { sfIconMap } from './components/icons-map';
export { AvailableSFSymbol } from './components/available-sfsymbols';